### ISSUE TITLE
Add support for newly supported languages

### ISSUE THREAD

**Issue by nedtwigg** [badsyntax/vscode-spotless-gradle#123]
Spotless 5.2.0 added support for black (python) and clang-format (c, c++, c#, objective-c, protobuf, javascript, and java).  So might want to hook into those VS Code project types as well.

**Comment by badsyntax** [comment]
I've added support for the following language types: `python`, `c`, `cpp`, `csharp`, `objective-c`, `objective-cpp`

Released with [1.0.2](https://github.com/badsyntax/vscode-spotless-gradle/releases/tag/1.0.2)
