### ISSUE TITLE
Improve changelog workflow

### ISSUE THREAD

**Issue by badsyntax** [badsyntax/vscode-spotless-gradle#19]
I added a mergeability app to check for changelog changes but this breaks CI when dependabot sends dep updates. As we're using GitHub releases & release drafter we don't need to keep a separate changelog updated.

- remove the mergability app
- update CHANGELOG.md to link to the releases page

**Comment by nedtwigg** [comment]
A brief plug for a related approach: https://github.com/diffplug/spotless-changelog

One of the things that project can do is machine-parse a changelog.  It's not built, but if you wanted to turn GitHub release metadata into a `CHANGELOG.md`, or vice-versa, all the changelog parsing / building code is in there, it would just need to get hooked into the GitHub APIs.  The only advantage imo of GitHub release metadata is API, at the cost of platform-lockin.  Standardized `CHANGELOG.md` gives you a broader and faster API without lockin.

**Comment by badsyntax** [comment]
I was never comfortable with removing the data from the CHANGELOG but found it to be a maintenance burden to keep the GitHub releases and the CHANGELOG in sync. Having an automated process would be ideal. I'll check this out when I got some time 👍

**Comment by nedtwigg** [comment]
I've added an [issue](https://github.com/diffplug/spotless-changelog/issues/10) for the specific topic of GitHub integration if you'd like to ignore broader noise on the project in favor of just this topic.
