### ISSUE TITLE
Wrong encoding results in file not being formatted

### ISSUE THREAD

**Issue by Woyten** [badsyntax/vscode-spotless-gradle#240]
We have UTF-8 Java files containing Umlauts (ä, ö, ü, ß). While `gradle spotlessApply` works reliably on those files, the `vscode-spotless-gradle` plugin doesn't. I guess the plugin does not parse the file content as UTF-8 but uses some default encoding (we use Microsoft Windows by the way).

**Comment by badsyntax** [comment]
@Woyten Can you provide an example of this? Would the following trigger the bug in your case?

```java
package gradle.project;

public class App {
  public static void main(String[] args) {
    String ä = "ä";
  }
}
```

**Comment by badsyntax** [comment]
I can't replicate on MacOS. 

I can replicate on Windows using the above code.

My Windows machine is painfully slow unfortunately.

It's difficult to tell where the problem might be as we're using the [`document.getText()`](https://github.com/badsyntax/vscode-spotless-gradle/blob/4c3d516a60b7b2e114d95b3377cfccc90834ca51/src/Spotless.ts#L76) api to get the document text which is then sent as stdin to the spotless gradle plugin. I will do some testing using the gradle wrapper from the cmd line using stdin with utf8 chars to determine if it's a spotless plugin issue (ideHook).

**Comment by badsyntax** [comment]
Test command:

```console
./gradlew spotlessApply -PspotlessIdeHook=/Users/richardwillis/Projects/badsyntax/vscode-spotless-gradle/test-fixtures/gradle-project/src/main/java/gradle/project/App.java -PspotlessIdeHookUseStdIn -PspotlessIdeHookUseStdOut --quiet <<< 'package gradle.project;public class App {public static void main(String[] args) {System.out.println("ä");}}'  
```

**Comment by badsyntax** [comment]
Windows test command (powershell):

```console
echo 'package gradle.project;public class App {public static void main(String[] args) {System.out.println("ä");}}' | & .\gradlew.bat spotlessApply -PspotlessIdeHook=C:\Users\richard.willis\Projects\badsyntax\vscode-spotless-gradle\test-fixtures\gradle-project\src\main\java\gradle\project\App.java -PspotlessIdeHookUseStdIn -PspotlessIdeHookUseStdOut --quiet
IS DIRTY
package gradle.project;

public class App {
  public static void main(String[] args) {
    System.out.println("?");
  }
}
```

It's not erroring, whereas this is the error as reported by the Gradle Tasks extension (which is not helpful):

```console
Error running build: spotlessApply -PspotlessIdeHook=C:\Users\richard.willis\Projects\badsyntax\vscode-spotless-gradle\test-fixtures\gradle-project\src\main\java\gradle\project\App.java -PspotlessIdeHookUseStdIn -PspotlessIdeHookUseStdOut --quiet: Could not execute build using Gradle distribution 'https://services.gradle.org/distributions/gradle-6.3-bin.zip'.
```

I will try debug the extension now.

**Comment by badsyntax** [comment]
I've been able to surface a better error message:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':spotlessApply'.
> Encoding error! Spotless uses UTF-8 by default.  At line 5 col 31:
  = "?";? <- UTF-8
  = "�";? <- windows-1252
  = "�";? <- ISO-8859-1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 454ms
```

**Comment by badsyntax** [comment]
@Woyten Unfortunately I need to do a lot more debugging to figure out where the issue is. I have a feeling this might be a problem with https://github.com/microsoft/vscode-gradle. Unfortunately I'm about to go on holiday and can only look at this next week. Sorry for the delay.

**Comment by badsyntax** [comment]
Possible related: https://github.com/microsoft/vscode-gradle/issues/1001

**Comment by Woyten** [comment]
@badsyntax Thanks for digging into this! The code example you proposed is a very good example for our problem. I will have a look at the code as well once I have the time for it.

**Comment by badsyntax** [comment]
@Woyten np! Would love to get to the bottom of this. My current theory is perhaps we just need to set the encoding in the relevant Gradle task settings but I don't have a computer right now to test that theory. I will do some more research tomorrow.

**Comment by badsyntax** [comment]
@Woyten Can you add the following to gradle.properties (either in your home directory, or in the root of your project):

```
org.gradle.jvmargs='-Dfile.encoding=UTF-8'
```

Can you let me know if that fixes things?

**Comment by Woyten** [comment]
@badsyntax Sorry for the late reply. For some reason, I did not get any notifications... The good news is: The problem seems to be fixed. :-) Thanks for your support!
