### ISSUE TITLE
Issue with vscode-gradle 3.7.0

### ISSUE THREAD

**Issue by brendansailer** [badsyntax/vscode-spotless-gradle#249]
I just upgraded to vscode-gradle 3.7.0 to fix issue with using a local version of Gradle.  However now I get the error: "Cannot activate the 'Spotless Gradle' extension because it depends on an unknown 'richardwillis.vscode-gradle' extension."

I think this should be an easy change to microsoft.vscode-gradle, but am unsure.  Thank you!

EDIT: It appears that badsyntax has been working diligently on this issue to resolve it.  Feel free to close out this issue once that's merged.

**Comment by badsyntax** [comment]
Thanks for the report. I've been working on adding support for 3.7.0 with https://github.com/badsyntax/vscode-spotless-gradle/pull/241

There a few other things we need to do but I'm expecting a new release in the next day, hopefully sooner.

**Comment by badsyntax** [comment]
This should be fixed now with  [1.1.4](https://github.com/badsyntax/vscode-spotless-gradle/releases/tag/1.1.4). Can you update and let me know if you experience any issues?

**Comment by brendansailer** [comment]
Awesome it works now - thank you for the update 👍  Many thanks :)

**Comment by badsyntax** [comment]
Great, thanks for verifying!
