### ISSUE TITLE
Incompatible with configuration cache

### ISSUE THREAD

**Issue by nedtwigg** [badsyntax/vscode-spotless-gradle#273]
See https://github.com/diffplug/spotless/issues/1082.

**Comment by badsyntax** [comment]
Thanks for letting me know. Seems like a minor change, will try make that change today.

**Comment by badsyntax** [comment]
@nedtwigg see https://github.com/badsyntax/vscode-spotless-gradle/pull/274

i haven't been able to replicate the issue unfortunately. i'll need clearer reproduction steps. 

i'll release the fix as is, but i would prefer to manually verify the change.

**Comment by badsyntax** [comment]
Released with [1.1.9](https://github.com/badsyntax/vscode-spotless-gradle/releases/tag/1.1.9).

**Comment by nedtwigg** [comment]
The reproduction would be any Gradle project with:

```properties
// gradle.properties
org.gradle.unsafe.configuration-cache=true
```

**Comment by badsyntax** [comment]
Thanks! I can now confirm the change fixes things.

Before:

```console
[error] [gradle-server] Could not execute build using Gradle distribution 'https://services.gradle.org/distributions/gradle-7.3.3-bin.zip'.
[error] Error running build: spotlessApply -PspotlessIdeHook=/Users/richardwillis/Projects/badsyntax/vscode-spotless-gradle/test-fixtures/gradle-project/src/main/java/gradle/project/App.java -PspotlessIdeHookUseStdIn -PspotlessIdeHookUseStdOut --quiet: Could not execute build using Gradle distribution 'https://services.gradle.org/distributions/gradle-7.3.3-bin.zip'.
```

After:

```console
[info] Completed build: spotlessApply -PspotlessIdeHook=/Users/richardwillis/Projects/badsyntax/vscode-spotless-gradle/test-fixtures/gradle-project/src/main/java/gradle/project/App.java -PspotlessIdeHookUseStdIn -PspotlessIdeHookUseStdOut --no-configuration-cache --quiet
```

**Comment by badsyntax** [comment]
Re-opened, as I want to add this to my tests.

**Comment by badsyntax** [comment]
@nedtwigg This change is now being tested as part the automated tests, see: https://github.com/badsyntax/vscode-spotless-gradle/pull/276

Good to close now.
