### ISSUE TITLE
No more Gradle tasks with Gradle extension

### ISSUE THREAD

**Issue by adr1enbe4udou1n** [badsyntax/vscode-spotless-gradle#284]
Hello,

Thanks for this nice extension 👍 

It perfectly worked last weeks but not anymore recently.

The official VS Code Gradle for Java 3.10 crashes when enabling this extension (version 1.2).

The "Refresh gradle tasks" command goes into `e.getDebuggable` error.

Gradle for Java output :

```
[info] Gradle Version: 7.3.3
[info] Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.3.3/userguide/command_line_interface.html#sec:command_line_warnings

CONFIGURE SUCCESSFUL in 5s
[error] Unable to refresh tasks: e.getDebuggable is not a function
```

Gradle tasks works fine when spotless gradle extension disabled.

Tested on Windows and Ubuntu on basic empty gradle project with minimal Java extensions without any specific settings.

Any idea ?

**Comment by badsyntax** [comment]
Thanks for the bug report. Will try investigate this week.

**Comment by badsyntax** [comment]
Apologies for the delay. I've released a fix with [1.2.1](https://github.com/badsyntax/vscode-spotless-gradle/releases/tag/1.2.1). Can you let me know if it fixes things for you?

**Comment by adr1enbe4udou1n** [comment]
It now works perfectly well, very thx 👍 
Just a last other problem under Windows which forces to have LF instead of default CRLF but not blocking for my needs ;)

**Comment by badsyntax** [comment]
Can you give some more information about that problem?

**Comment by adr1enbe4udou1n** [comment]
Just initialize a new spring boot project with all basic spotless settings under Windows (mayby you can try linux too)

Then if your file is on CRLF :

![image](https://user-images.githubusercontent.com/3679080/153495669-0ea21208-d942-4a3c-8628-6cab8ec7daa1.png)

But I'm pretty sure it comes from spotless config, not from your plugin, a simple ".\gradlew spotlessApply" converts all files to LF and this problems gones ;)
